#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const vm = require('vm');

function escapeForSingleQuotedString(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t')
    .replace(/'/g, "\\'");
}

function isValidIdentifier(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

function extractBootstrap(source) {
  const bootstrapStart = source.indexOf('function stringTableSource()');
  if (bootstrapStart === -1) {
    throw new Error('未找到 stringTableSource，当前脚本只支持这类字符串表混淆结构。');
  }

  const bootstrapMarker = '}(stringTableSource';
  const bootstrapCallIndex = source.indexOf(bootstrapMarker, bootstrapStart);
  if (bootstrapCallIndex === -1) {
    throw new Error('未找到字符串表初始化 IIFE。');
  }

  const nextFactoryIndex = source.indexOf(',\nfunction() {', bootstrapCallIndex);
  if (nextFactoryIndex === -1) {
    throw new Error('未找到 bootstrap 结束位置。');
  }

  return source.slice(bootstrapStart, nextFactoryIndex);
}

function buildDecodeRuntime(source) {
  const bootstrapCode = `${extractBootstrap(source)});\n`;
  const sandbox = {
    console: {
      log() {},
      error() {},
      warn() {},
      info() {}
    }
  };
  vm.createContext(sandbox);
  vm.runInContext(bootstrapCode, sandbox, {
    timeout: 3000,
    filename: 'tmp-bootstrap.js'
  });

  if (typeof sandbox.decodeString !== 'function') {
    throw new Error('bootstrap 执行后没有得到 decodeString 函数。');
  }

  return sandbox.decodeString;
}

function replaceDecodeCalls(source, decodeString) {
  const decodeCallPattern = /\bdecodeString\(\s*(0x[0-9a-fA-F]+|\d+)\s*(?:,\s*([^()]*?))?\)/g;
  return source.replace(decodeCallPattern, (match, rawIndex, secondArg) => {
    try {
      const indexValue = Number(rawIndex);
      const decoded = decodeString(indexValue, secondArg);
      if (typeof decoded !== 'string') {
        return match;
      }
      return `'${escapeForSingleQuotedString(decoded)}'`;
    } catch (_error) {
      return match;
    }
  });
}

function cleanupReadablePatterns(source) {
  let output = source;

  output = output.replace(/\[\s*'([A-Za-z_$][A-Za-z0-9_$]*)'\s*\]/g, '.$1');
  output = output.replace(/!!\[\]/g, 'true');
  output = output.replace(/!\[\]/g, 'false');
  output = output.replace(/\bvoid\s+\([^)]+\)/g, 'undefined');

  output = output.replace(
    /([A-Za-z_$][A-Za-z0-9_$]*)\['([^']+)'\]/g,
    (match, objectName, propertyName) => {
      if (!isValidIdentifier(propertyName)) {
        return match;
      }
      return `${objectName}.${propertyName}`;
    }
  );

  return output;
}

function main() {
  const inputPath = process.argv[2]
    ? path.resolve(process.cwd(), process.argv[2])
    : path.resolve(process.cwd(), 'duitang/tmp.js');
  const outputPath = process.argv[3]
    ? path.resolve(process.cwd(), process.argv[3])
    : inputPath.replace(/\.js$/, '.readable.js');

  const source = fs.readFileSync(inputPath, 'utf8');
  const decodeString = buildDecodeRuntime(source);

  let output = source;
  output = replaceDecodeCalls(output, decodeString);
  output = cleanupReadablePatterns(output);

  const banner = [
    '// Decompiled helper output generated by duitang/deobfuscate.js',
    '// Passes applied:',
    '// 1. bootstrap runtime evaluation to recover decodeString()',
    '// 2. decodeString(...) call replacement',
    '// 3. simple readability cleanup for property access and boolean literals',
    ''
  ].join('\n');

  fs.writeFileSync(outputPath, banner + output, 'utf8');
  console.log(`input : ${inputPath}`);
  console.log(`output: ${outputPath}`);
}

main();
